# Generated by Django 5.2.4 on 2025-07-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('image', models.ImageField(upload_to='screenshots/')),
            ],
        ),
    ]
