# Generated by Django 5.2.4 on 2025-07-23 06:41

import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshotlog',
            name='image',
            field=models.ImageField(upload_to=monitoring.models.user_directory_path),
        ),
    ]
