# Generated by Django 5.2.4 on 2025-07-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_screenshotlog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshotlog',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='screenshotlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screenshotlog',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
